### ISSUE TITLE
Why does it require "read your browsing history" permission now?

### ISSUE THREAD

**Issue by rongi** [stefansundin/duplicate-tab#5]

**Comment by stefansundin** [comment]
It's because of #3. You can always download the source code and use the old version if you wish.

**Comment by bbarenblat** [comment]
One could use the [optional permissions API](https://developer.chrome.com/apps/permissions) to request the browsing history permission only when the user enables that setting. I’d be happy to write the code once https://github.com/stefansundin/duplicate-tab/issues/4 gets fixed.

**Comment by stefansundin** [comment]
I totally forgot optional permissions are a thing, I'll give it a try this weekend.

**Comment by stefansundin** [comment]
I just released a new Chrome version that uses the optional permissions API. You'll have to uninstall and the install the extension to revoke the tabs permissions from the extension.

Unfortunately, because of https://bugzilla.mozilla.org/show_bug.cgi?id=1422605, I didn't get the same thing to work in Firefox just yet. Hopefully they'll fix it soon.

**Comment by stefansundin** [comment]
I just released v1.5.0, and now Firefox also uses optional permissions. 🎉
