### ISSUE TITLE
Add shortcut for duplicating tab into new window

### ISSUE THREAD

**Issue by bbarenblat** [stefansundin/duplicate-tab#7]
I’d love a second shortcut to not only duplicate the tab but to duplicate it into a new window.

**Comment by stefansundin** [comment]
This was implemented in https://github.com/stefansundin/duplicate-tab/commit/fedb00701fecf422472a09945b405f50151d0de4. I went through a couple iterations until I got it just right. I hope you like it.

Note that this requires giving the extension the tabs permission, as otherwise it doesn't have access to the `tab.url` property: https://github.com/stefansundin/duplicate-tab/blob/797f558eab64041add37cf8f40f3be16066ee18b/chrome/background.js#L77
